### ISSUE TITLE
Addition of basic coding questions

### ISSUE THREAD

**Issue by Harish-2003** [animator/learn-python#127]
I would love to add some basic coding questions such as 

1. Printing 1 to n numbers
2. Printing n to 1 numbers
3. Reverse of a Number
4. Palindrome
5. Armstrong
6. Strong
7. Prime
8. N primes and lot more based upon your requirments
@animator

**Comment by SaiSruthisri** [comment]
Hi would you please mind adding the gssoc'24 label & appropriate level(1/2/3) to it .
Thank you.
I would like to add some of most commonly practice questions to this
1. If  given number is odd or even.
2. Find the given number is positive or negative
3. Sum of two numbers
4. Prime or not.
5. Palindrome or not
6. Armstrong
7. Anagram
8. Maximum/minimum  of 3 numbers.
9.  Factorial
10. Fibonacci
11. GCD of two numbers
12. Printing patterns.

My approach:
For each & every question I am thinking to add description about the things described  in the question. 
For example Say the question is about anagram a little description about what anagram is would greatly help while learning  
If any pictorial examples are possible would add it to.
Please consisder assigning this task to me.

**Comment by JanitKumar** [comment]
I can add below is the sample and I can add more than that please assign it to me @animator 

1. **Calculate the multiplication and sum of two numbers:**
   - Given two integer numbers, return their product only if the product is equal to or lower than 1000. Otherwise, return their sum.

2. **Print the sum of the current number and the previous number:**
   - Write a program to iterate through the first 10 numbers and, in each iteration, print the sum of the current and previous number.

3. **Print characters from a string that are present at an even index number:**
   - Accept a string from the user and display characters that are present at an even index number.

4. **Remove first n characters from a string:**
   - Write a program to remove characters from a string starting from zero up to n and return a new string.

5. **Calculate average expenses for each semester:**
   - John has a list of his monthly expenses from last year. Calculate his average expenses for the first semester (January to June) and the second semester (July to December).

6. **Check if a value exists within a list:**
   - Write a program to check if a given value exists within a list.

7. **Calculate the result of a mathematical expression:**
   - Given an expression, evaluate it using Python's operator precedence rules.

8. **Print characters from a string in reverse order:**
   - Accept a string from the user and print its characters in reverse order.

9. **Create a function with default arguments:**
   - Write a function that takes two arguments, with one of them having a default value.

10. **Manipulate a list:**
    - Perform various operations on a list, such as appending, removing duplicates, and slicing.

11. **Work with dictionaries:**
    - Practice dictionary operations like adding, updating, and accessing elements.

12. **Use loops and conditionals:**
    - Solve problems involving loops, if-else statements, and while loops.

13. **Understand string operations:**
    - Practice string manipulations and slicing.

14. **Learn about date and time:**
    - Solve questions related to date, time, and datetime objects.

15. **Explore object-oriented programming (OOP):**
    - Understand OOP concepts by solving relevant exercises.

Feel free to tackle these exercises and have fun learning! 😊

Source: Conversation with Bing, 12/5/2024
(1) Python Basic Exercise for Beginners with Solutions - PYnative. https://pynative.com/python-basic-exercise-for-beginners/.
(2) Python Practice for Beginners: 15 Hands-On Problems. https://learnpython.com/blog/python-practice-for-beginners/.
(3) Basic Python Quiz For Beginners - PYnative. https://pynative.com/basic-python-quiz-for-beginners/.
(4) Python Exercise with Practice Questions and Solutions. https://www.geeksforgeeks.org/python-exercises-practice-questions-and-solutions/.
(5) Python Quiz - W3Schools. https://www.w3schools.com/python/python_quiz.asp.
(6) Python Basics Quiz Test - W3docs. https://www.w3docs.com/quiz-start/python-basics.
(7) Python Knowledge Quiz (Beginner) - Code Conquest. https://www.codeconquest.com/coding-quizzes/python-knowledge-quiz-beginner/.
(8) Welcome to 101 Exercises for Python Fundamentals. https://colab.research.google.com/github/ryanorsinger/101-exercises/blob/main/101-exercises.ipynb.
(9) 10 Python Practice Exercises for Beginners with Solutions. https://learnpython.com/blog/python-practice-exercises-for-beginners/.
(10) Python Exercises for Beginners: Build Your Coding Foundation - TechBeamers. https://techbeamers.com/python-exercises-for-beginners/.
(11) Python Exercises, Practice, Challenges – PYnative. https://pynative.com/python-exercises-with-solutions/.
(12) Exercises and Solutions - Practice Python. https://www.practicepython.org/exercises/.
(13) Python Exercises - W3Schools. https://www.w3schools.com/python/python_exercises.asp.
(14) Python Exercises for Beginners: Solve 100+ Coding Challenges. https://www.udemy.com/course/python-exercises-for-beginners-solve-coding-challenges/.

**Comment by animator** [comment]
We are not accepting any practice coding questions. Pick another topic and raise a new issue.
