### ISSUE TITLE
Remove Extra point on Leaderboard: Gssoc review Team

### ISSUE THREAD

**Issue by sanjay-kv** [animator/learn-python#1313]
https://github.com/animator/learn-python/pull/579
![image](https://github.com/animator/learn-python/assets/30715153/c7f0da8a-750a-46b6-8148-cb1ebe50e6ae)

**Comment by ashitaprasad** [comment]
@sanjay-kv The levels of the following PRs have been reduced so that the point do not exceed 150 
https://github.com/animator/learn-python/pull/579 https://github.com/animator/learn-python/pull/891 https://github.com/animator/learn-python/pull/1111 https://github.com/animator/learn-python/pull/674 https://github.com/animator/learn-python/pull/536 https://github.com/animator/learn-python/pull/449 https://github.com/animator/learn-python/pull/207

**Comment by sanjay-kv** [comment]
have you communicated with the contributor @Santhosh-Siddhardha regarding this?

its important to communicate with them regarding this, sudden level down of 5 to 8 PR without informing will affect the program and project admins. @animator 
sample communication: 
![image](https://github.com/animator/learn-python/assets/30715153/1076fdea-3c7d-4883-bf4c-dd39fdc19b9a)

![image](https://github.com/animator/learn-python/assets/30715153/bd32a65a-0b55-495f-bd0c-d88e31d12057)
