### ISSUE TITLE
Missing CODE_OF_CONDUCT.md file in repository

### ISSUE THREAD

**Issue by tupur-29** [animator/learn-python#152]
The repository currently lacks a CODE_OF_CONDUCT.md file which is an important resource for fostering a welcoming and inclusive environment within our community.

Please assign this issue to me under GSSOC'24

Could you please add label to this issue?

**Comment by vanshikab52** [comment]
A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions. It sets clear guidelines for expected behavior and helps ensure that all contributors feel safe and respected.
@animator You can assign this issue to me as I'm working under GSSoC'24 as a contributor. I can add a code of conduct to this project.
Thanks

**Comment by animator** [comment]
Done 🫡
